from src.texts.common import (
    ASK_LOCATION_TEXT,
    MAP_LOCAL_TEXT,
    MAP_OPEN_TEXT,
    MAP_URL_TEXT,
    MISSING_MEDIA_TEXT,
    NEED_LOCATION_TEXT,
    NEED_MEDIA_TEXT,
    SAVED_TEXT,
    START_MESSAGE,
    WEBAPP_URL_MISSING,
)

__all__ = [
    "ASK_LOCATION_TEXT",
    "MAP_LOCAL_TEXT",
    "MAP_OPEN_TEXT",
    "MAP_URL_TEXT",
    "MISSING_MEDIA_TEXT",
    "NEED_LOCATION_TEXT",
    "NEED_MEDIA_TEXT",
    "SAVED_TEXT",
    "START_MESSAGE",
    "WEBAPP_URL_MISSING",
]
